/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/van_gogh.gltf -o app/components/models/Van.tsx --types 
Author: Sketchfab (https://sketchfab.com/Sketchfab)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/camera-limits-demo-van-gogh-bedroom-in-arles-daefab319a584e559443e39ff05e84fa
Title: Camera Limits Demo: Van Gogh - Bedroom in Arles
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh
    Object_3: THREE.Mesh
    Object_4: THREE.Mesh
    Object_5: THREE.Mesh
    Object_6: THREE.Mesh
    Object_7: THREE.Mesh
    Object_8: THREE.Mesh
    Object_9: THREE.Mesh
    Object_10: THREE.Mesh
    Object_11: THREE.Mesh
    Object_12: THREE.Mesh
    Object_13: THREE.Mesh
    Object_14: THREE.Mesh
    Object_15: THREE.Mesh
    Object_16: THREE.Mesh
    Object_17: THREE.Mesh
  }
  materials: {
    ['13___Default']: THREE.MeshBasicMaterial
    ['13___Defaultdddddd']: THREE.MeshBasicMaterial
    ['13___Defaultdddddddddddddd']: THREE.MeshBasicMaterial
    ['13___Defaultddddddddddddddddddd']: THREE.MeshBasicMaterial
    ['13___Defaultdddddddddddddddddddd']: THREE.MeshBasicMaterial
    ['13___Defaultd']: THREE.MeshBasicMaterial
    ['13___Defaultddd']: THREE.MeshBasicMaterial
    ['13___Defaultddddd']: THREE.MeshBasicMaterial
    ['13___Defaultdddddddd']: THREE.MeshBasicMaterial
    ['13___Defaultddddddddd']: THREE.MeshBasicMaterial
    ['13___Defaultddddddddddd']: THREE.MeshBasicMaterial
    ['13___Defaultdddddddddddd']: THREE.MeshBasicMaterial
    ['13___Defaultddddddddddddd']: THREE.MeshBasicMaterial
    ['13___Defaultddddddddddddddd']: THREE.MeshBasicMaterial
    ['13___Defaultdddddddddddddddd']: THREE.MeshBasicMaterial
  }
  //animations: GLTFAction[]
}

export function Wanderer(props: React.JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/van_gogh.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={1.005}>
        <mesh geometry={nodes.Object_2.geometry} material={materials['13___Default']} />
        <mesh geometry={nodes.Object_3.geometry} material={materials['13___Defaultdddddd']} />
        <mesh geometry={nodes.Object_4.geometry} material={materials['13___Defaultdddddddddddddd']} />
        <mesh geometry={nodes.Object_5.geometry} material={materials['13___Defaultddddddddddddddddddd']} />
        <mesh geometry={nodes.Object_6.geometry} material={materials['13___Defaultdddddddddddddddddddd']} />
        <mesh geometry={nodes.Object_7.geometry} material={materials['13___Defaultd']} />
        <mesh geometry={nodes.Object_8.geometry} material={materials['13___Defaultddd']} />
        <mesh geometry={nodes.Object_9.geometry} material={materials['13___Defaultddddd']} />
        <mesh geometry={nodes.Object_10.geometry} material={materials['13___Defaultdddddddd']} />
        <mesh geometry={nodes.Object_11.geometry} material={materials['13___Defaultdddddddd']} />
        <mesh geometry={nodes.Object_12.geometry} material={materials['13___Defaultddddddddd']} />
        <mesh geometry={nodes.Object_13.geometry} material={materials['13___Defaultddddddddddd']} />
        <mesh geometry={nodes.Object_14.geometry} material={materials['13___Defaultdddddddddddd']} />
        <mesh geometry={nodes.Object_15.geometry} material={materials['13___Defaultddddddddddddd']} />
        <mesh geometry={nodes.Object_16.geometry} material={materials['13___Defaultddddddddddddddd']} />
        <mesh geometry={nodes.Object_17.geometry} material={materials['13___Defaultdddddddddddddddd']} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/van_gogh.glb')
